<Project>
  <PropertyGroup>
    <BaseOutputPath>$(MSBuildThisFileDirectory)out\build\$(MSBuildProjectName)\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)out\build\$(MSBuildProjectName)\obj\</BaseIntermediateOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildThisFileDirectory)out\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
