<#
.SYNOPSIS
    Zero-dependency installer for Huaxiazi (no Inno Setup required).

.DESCRIPTION
    Copies the self-contained publish output (out\publish\win-x64\) to
        %ProgramFiles%\Huaxiazi\
    creates a Start Menu shortcut and a Desktop shortcut, writes an uninstall
    registry entry, and generates a self-contained uninstall.ps1 next to the
    installed binaries.

    SAFETY / ROBUSTNESS:
      * Idempotent: re-running overwrites in place without errors.
      * Handles an existing install directory gracefully (updates it).
      * Elevation: requires an administrator token and a target below Program Files.
        This prevents a standard user from replacing application DLLs or the
        generated uninstall helper after installation.
      * Zero external dependencies: only built-in PowerShell + WScript.Shell COM.

.PARAMETER SourceDir
    Folder with the published binaries (default: <repo root>\out\publish\win-x64).

.PARAMETER InstallDir
    Install target (default: %ProgramFiles%\Huaxiazi). Custom targets must remain
    below %ProgramFiles% and the script must run elevated.

.PARAMETER Force
    Reinstall even if the target directory already exists (default behaviour also
    updates in place, this just suppresses the "already installed" notice).

.EXAMPLE
    # Right-click -> "Run with PowerShell"
    .\install.ps1
#>

[CmdletBinding()]
param(
    [string]$SourceDir  = "",
    [string]$InstallDir = "",
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$RepoRoot  = Split-Path -Parent $ScriptDir

if ([string]::IsNullOrWhiteSpace($SourceDir)) {
    $SourceDir = Join-Path $RepoRoot "out\publish\win-x64"
}
if (-not [System.IO.Path]::IsPathRooted($SourceDir)) {
    $SourceDir = Join-Path $RepoRoot $SourceDir
}
$SourceDir = [System.IO.Path]::GetFullPath($SourceDir)

if ([string]::IsNullOrWhiteSpace($InstallDir)) {
    $InstallDir = Join-Path $env:ProgramFiles "Huaxiazi"
}
$InstallDir = [System.IO.Path]::GetFullPath($InstallDir)

$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    throw "此安装程序必须以管理员身份运行，才能将程序安装到受保护的 Program Files 目录。"
}

$programFilesRoot = [System.IO.Path]::GetFullPath($env:ProgramFiles).TrimEnd([IO.Path]::DirectorySeparatorChar) + [IO.Path]::DirectorySeparatorChar
if (-not $InstallDir.StartsWith($programFilesRoot, [StringComparison]::OrdinalIgnoreCase)) {
    throw "安装目录必须位于受保护的 Program Files 目录下。"
}

$AppExe       = Join-Path $InstallDir "Huaxiazi.exe"
$SourceExe    = Join-Path $SourceDir "Huaxiazi.exe"
$AppName      = "话匣子"
$UninstallKey = "Software\Microsoft\Windows\CurrentVersion\Uninstall\Huaxiazi"

function Write-Step([string]$msg) {
    Write-Host ""
    Write-Host "============================================================" -ForegroundColor Cyan
    Write-Host "  $msg" -ForegroundColor Cyan
    Write-Host "============================================================" -ForegroundColor Cyan
}

function New-Shortcut([string]$linkPath, [string]$targetPath, [string]$workingDir, [string]$description) {
    $ws  = New-Object -ComObject WScript.Shell
    $lnk = $ws.CreateShortcut($linkPath)
    $lnk.TargetPath       = $targetPath
    $lnk.WorkingDirectory = $workingDir
    $lnk.Description       = $description
    $lnk.IconLocation      = "$targetPath,0"
    $lnk.Save()
}

# ---------- 0. Preconditions ----------
Write-Step "话匣子安装程序"
if (-not (Test-Path $SourceDir)) {
    Write-Error "Source directory not found: $SourceDir`nPlease run 'dotnet publish' (or publish.ps1) first."
    exit 1
}
if (-not (Test-Path $SourceExe -PathType Leaf)) {
    Write-Error "Huaxiazi.exe not found in source: $SourceDir`nPublish the self-contained build first."
    exit 1
}

# Read display version from the executable (falls back to 1.0.0).
$displayVersion = "2.0.0"
try {
    $vi = (Get-Item $SourceExe).VersionInfo
    if (-not [string]::IsNullOrWhiteSpace($vi.FileVersion)) { $displayVersion = $vi.FileVersion }
}
catch {
    # keep default
}

# ---------- 1. Copy files (idempotent) ----------
Write-Step "Copying files to $InstallDir"
if (Test-Path $InstallDir) {
    Write-Host "Target already exists; updating in place." -ForegroundColor Yellow
}
else {
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
}
Copy-Item -Path (Join-Path $SourceDir "*") -Destination $InstallDir -Recurse -Force
Write-Host "Files copied." -ForegroundColor Green

# ---------- 2. Generate self-contained uninstall.ps1 ----------
Write-Step "Writing uninstall helper"
$uninstallLines = @(
    "# Auto-generated by deploy/install.ps1 - do not edit."
    ('$InstallDir = "' + $InstallDir + '"')
    ('$StartMenu   = "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\' + $AppName + '.lnk"')
    ('$Desktop     = "$env:USERPROFILE\Desktop\' + $AppName + '.lnk"')
    'try { if (Test-Path $StartMenu) { Remove-Item $StartMenu -Force } } catch {}'
    'try { if (Test-Path $Desktop)   { Remove-Item $Desktop -Force } } catch {}'
    'try { if (Test-Path $InstallDir) { Remove-Item $InstallDir -Recurse -Force } } catch {}'
    ('try { Remove-Item "HKCU:\' + $UninstallKey + '" -Force -ErrorAction SilentlyContinue } catch {}')
    ('try { Remove-Item "HKLM:\' + $UninstallKey + '" -Force -ErrorAction SilentlyContinue } catch {}')
    'Write-Host "话匣子已卸载；用户资料仍保留在 %LocalAppData%\Huaxiazi。"'
)
$uninstallBody = $uninstallLines -join [Environment]::NewLine
$uninstallScript = Join-Path $InstallDir "uninstall.ps1"
Set-Content -Path $uninstallScript -Value $uninstallBody -Encoding UTF8
Write-Host "Uninstall helper: $uninstallScript" -ForegroundColor Green

# ---------- 3. Shortcuts ----------
Write-Step "Creating shortcuts"
$startMenuDir = Join-Path $env:APPDATA "Microsoft\Windows\Start Menu\Programs"
$startMenuLnk = Join-Path $startMenuDir "$AppName.lnk"
$desktopLnk   = Join-Path $env:USERPROFILE "Desktop\$AppName.lnk"

New-Item -ItemType Directory -Path $startMenuDir -Force | Out-Null
New-Shortcut -linkPath $startMenuLnk -targetPath $AppExe -workingDir $InstallDir -description $AppName
New-Shortcut -linkPath $desktopLnk   -targetPath $AppExe -workingDir $InstallDir -description $AppName
Write-Host "Start Menu : $startMenuLnk" -ForegroundColor Green
Write-Host "Desktop    : $desktopLnk" -ForegroundColor Green

# ---------- 4. Uninstall registry (HKLM -> HKCU fallback) ----------
Write-Step "Writing uninstall registry entry"
$uninstallString = "powershell.exe -ExecutionPolicy Bypass -File `"$uninstallScript`""

function Set-UninstallEntry([string]$root) {
    $key = "$root\$UninstallKey"
    if (-not (Test-Path $key)) { New-Item -Path $key -Force | Out-Null }
    New-ItemProperty -Path $key -Name "DisplayName"     -Value $AppName       -PropertyType String -Force | Out-Null
    New-ItemProperty -Path $key -Name "DisplayVersion"  -Value $displayVersion -PropertyType String -Force | Out-Null
    New-ItemProperty -Path $key -Name "Publisher"       -Value $AppName       -PropertyType String -Force | Out-Null
    New-ItemProperty -Path $key -Name "InstallLocation" -Value $InstallDir    -PropertyType String -Force | Out-Null
    New-ItemProperty -Path $key -Name "UninstallString" -Value $uninstallString -PropertyType String -Force | Out-Null
    New-ItemProperty -Path $key -Name "NoModify"        -Value 1              -PropertyType DWord  -Force | Out-Null
    New-ItemProperty -Path $key -Name "NoRepair"        -Value 1              -PropertyType DWord  -Force | Out-Null
}

$registryWritten = $false
if ($isAdmin) {
    try {
        Set-UninstallEntry -root "HKLM:"
        Write-Host "Uninstall entry written to HKLM." -ForegroundColor Green
        $registryWritten = $true
    }
    catch {
        Write-Host "HKLM write failed: $($_.Exception.Message). Falling back to HKCU." -ForegroundColor Yellow
    }
}

if (-not $registryWritten) {
    try {
        Set-UninstallEntry -root "HKCU:"
        Write-Host "Uninstall entry written to HKCU (per-user)." -ForegroundColor Green
    }
    catch {
        Write-Warning "Could not write uninstall registry entry: $($_.Exception.Message)"
    }
}

Write-Step "Installation complete"
Write-Host "话匣子已安装到: $InstallDir" -ForegroundColor Green
Write-Host "Run '$AppName' from the Start Menu or Desktop shortcut." -ForegroundColor Green
